version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: chatgpt-slackbot${NAME_SUFFIX}
    env_file:
      - opt/.env
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt